apiVersion: model.aibrix.ai/v1alpha1
kind: ModelAdapter
metadata:
  name: code-lora
  namespace: default
  labels:
    model.aibrix.ai/name: code-lora
    model.aibrix.ai/port: "8000"
spec:
  baseModel: llama32-3b-instruct
  podSelector:
    matchLabels:
      model.aibrix.ai/name: llama32-3b-instruct
      adapter.model.aibrix.ai/enabled: "true"
  artifactURL: /home/qhq/serverless_llm_experiment/artifacts/frozen/llama32_3b_a500_v1_modelscope/code_lora
  schedulerName: default
  additionalConfig:
    rank: "8"
    alpha: "16"
    timeout: "120s"
